.travis.yml
Rakefile

Travis CI runs rake by default to execute your tests.
You could use only `rake` to run all test suite.

Make :test a default rake task

---

lib/active_scaffold/helpers/form_column_helpers.rb

Tested this, Recordselect seems to work fine when js_framework is :jquery, so instead just ensure that js_framework isn't nil.  Also considered just removing the check altogether, not sure if one makes more sense over the other.

enable recordselect for add existing when js_framework == :jquery

---

app/assets/javascripts/jquery/tiny_mce_bridge.js
app/assets/javascripts/prototype/tiny_mce_bridge.js
lib/active_scaffold/bridges/tiny_mce/helpers.rb
test/bridges/tiny_mce_test.rb

pull request created as per your request on the ActiveScaffold : Ruby on Rails Gem Google group regarding TinyMCE.
Using rails 4.2,  tinymce-rails (4.1.6) and active_scaffold (3.4.18.1), in order to get the tinymce bridge to work, I had to make the following changes to active_scaffold:
In TinyMCE 4.x mceRemoveControl and mceAddControl have been removed. 
Search and replace all occurrences with mceRemoveEditor and mceAddEditor instead.
The standard theme is not part of the tinymce-rails gem.
In lib/active_scaffold/bridges/tiny_mce/helpers.rb, change line 18 :
settings = {:theme => 'standard'}.merge(column.options[:tinymce] || {})
to
settings = {:theme => 'modern'}.merge(column.options[:tinymce] || {})

update tinyMCE bridge with changed commands and theme

---

CODE_OF_CONDUCT.md

Please, review before merging: this isn't a bugfix or enhancement, but rather proposition to approve ethical Code of Conduct promising other contributors treatment with respect and without discrimination.
I've accepted it for all of my own projects too.

Introduced Code of Conduct from http://contributor-covenant.org/

---

lib/active_scaffold/actions/core.rb

Currently set_parent uses the parent controller name to set the parent model. 
This does not work correctly when the controller is not named according to the standard convention (for example when the parent controller is in a namespace and its model is not).
Changed to look up the parent model from the parent controller's active_scaffold_config.

Use parent controller config to get parent model

---

lib/active_scaffold/actions/common_search.rb
lib/active_scaffold/actions/core.rb
lib/active_scaffold/actions/create.rb
lib/active_scaffold/actions/delete.rb
lib/active_scaffold/actions/list.rb
lib/active_scaffold/actions/mark.rb
lib/active_scaffold/actions/nested.rb
lib/active_scaffold/actions/show.rb
lib/active_scaffold/actions/update.rb
lib/active_scaffold/active_record_permissions.rb
lib/active_scaffold/bridges/cancan/cancan_bridge.rb
test/misc/attribute_params_test.rb
test/misc/constraints_test.rb

Old syntax is deprecated in Rails 5.0 and will be removed in Rails 5.1.
See https://github.com/rails/rails/blob/master/actionpack/lib/abstract_controller/callbacks.rb
The same as in https://github.com/activescaffold/active_scaffold/pull/451 but rebased on `next` branch.

Using new syntax: *_action instead of *_filter

---

app/views/active_scaffold_overrides/on_update.js.erb

1. Uses explicit comparison to 'true' (```if params[:dont_close] == 'true'```) to avoid case where parameter is 'false' but ```if params[:dont_close]``` is truthy. Also matches ```params[:iframe]``` tests elsewhere in file.
2. Fixes ```<%= "ActiveScaffold.enable_form('#{form_selector}');"...%>``` form which escapes the single quotes and doesn't work.

Fix Javascript escaping in :dont_close path of on_update

---

lib/active_scaffold/bridges/tiny_mce/helpers.rb
test/bridges/tiny_mce_test.rb

Currently the bridge does not support the workflow outlined in [the readme of the tinymce-rails gem](https://github.com/spohlenz/tinymce-rails/blob/master/README.md). This patch will allow for the use of the tinymce.yml file and introduce a way to configure specific columns to use other configurations (:tinymce_configuration).
Also to reflect that the :text_editor form_ui option is very tinymce specific, allow form_ui to be :tinymce

Make the TinyMCE bridge integrate better with the tinymce-rails gem

---

lib/active_scaffold/data_structures/column.rb

In ActiveModel 3.2.22.2 the symbol used for possible values in the
InclusionValidator is :in. Add it and use it if none of the others are
found.

Inclusion_validator_for_checkbox didn't pick up val options for rails 3

---

lib/active_scaffold/actions/subform.rb

When the subform is nested below another controller, then the
parent_record must be rendered, with the selected record in an
appropriate subform.
The previous code caused associations to be save on selection, instead
of rendering a form with an unsaved record.

Bugfix select of existing record for nested subform.

---

lib/active_scaffold/actions/subform.rb

The previous commit to this file was cleaned up before the pull request,
but a variable rename was only partially done.
This fixes the problem.

Bugfix variable name in nested subforms.

---

lib/active_scaffold/helpers/view_helpers.rb

Original deprecation warning:
> DEPRECATION WARNING: Method to_a is deprecated and will be removed in Rails 5.1, as `ActionController::Parameters` no longer inherits from hash. Using this deprecated behavior exposes potential security problems. If you continue to use this method you may be creating a security vulnerability in your app that can be exploited. Instead, consider using one of these documented methods which are not deprecated: http://api.rubyonrails.org/v5.0.0.1/classes/ActionController/Parameters.html (called from action_link_selected? at /Users/david/.rvm/gems/ruby-2.3.0/bundler/gems/active_scaffold-ab6218d9ad5d/lib/active_scaffold/helpers/view_helpers.rb:379)

Fix Rails 5 deprecation warning " Method to_a is deprecated"

---

app/assets/javascripts/active_scaffold.js.erb

jQuery-ui 6 changes: sortable, draggable, droppable and datepicker have
been moved to widgets directory.

Fix jQuery-ui 6.0 (rails 4.2.7)

---

app/views/active_scaffold_overrides/_base_form.html.erb

This is useful in some of the active_scaffold_export forks to be able to disable the loading indicator, which does not work correctly for export.

Allows data-loading to be optionally set on the base form

---

lib/active_scaffold/extensions/action_view_rendering.rb

issue where the EID hash length can overflow the session cookie
store when rendering many embedded scaffolds with conditions at a
time. Fixes issue #536. The long-term fix should be to replace the
use of the session with something else for :conditions and :constraints.

Revert commit SHA: 5e2bcef8232f0f9dba0bfc7c09786f5ad34ed2af to fix

---

lib/active_scaffold/actions/nested.rb

The shallow delete option described on the [wiki](https://github.com/activescaffold/active_scaffold/wiki/API%3A-Nested#shallow_delete-v11-global-local) currently does not seem to work. The `lib/active_scaffold/actions/nested.rb` file tries to delete the `delete` action when it should be called `destroy`.

Fixes the `shallow_delete` for nested habtm relations.

---

app/assets/javascripts/active_scaffold.js.erb

it seems in Jquery-rails gem version 6.0.1, the pathing has changed.
I'm not fully cognizant of the exact jquery-rails versions that match which pathing schemes.

Fix https://github.com/activescaffold/active_scaffold/issues/543

---

lib/active_scaffold/helpers/list_column_helpers.rb
lib/active_scaffold/helpers/pagination_helpers.rb

In controllers with the `:search` action disabled AND `config.store_user_settings = false` AND `clear_helpers` I would receive this error:
```
An ActionView::Template::Error occurred in consultations#index:
undefined local variable or method `search_params' for #<#<Class:0x00000008a03ae0>:0x0000000cdb1e18>
```
After some debugging, it appears that there is a missing `respond_to?` check in some of the other included helpers.  This PR adds them and resolves the issue

Fix for undefined method 'search_params'

---

lib/active_scaffold/data_structures/column.rb

The flag :within is no longer there for InclusionValidator for
booleans in latest Rails 4.2, and the function description for
validates_inclusion_of()[[1]] states that :within is an alias for :in,
so using that if it exists should ammount for the same.
[1]: https://github.com/rails/rails/blob/20c91119903f70eb19aed33fe78417789dbf070f/activemodel/lib/active_model/validations/inclusion.rb

Add :in to the list of values checked for booleans in inclusion_validator_for_checkbox?(val)

---

app/assets/javascripts/jquery/date_picker_bridge.js.erb

Setting options on the date_picker plugin with a value of `false` fails due to a naive comparison in this conditional.  I believe comparing to `undefined` is correct, and resolves this issue.

Allow setting of 'false' value for date_picker options

---

lib/active_scaffold/engine.rb
lib/active_scaffold/extensions/connection_adapter.rb

I believe SQL Server needs the same special handling that was added for PostgreSQL in #502.
For SQL Server, if the list is being sorted by a column that is not displayed in the list, you end up with an error like this:
`
TinyTds::Error: ORDER BY items must appear in the select list if SELECT DISTINCT is specified.: EXEC sp_executesql N'SELECT  DISTINCT [patient_logs].* FROM [patient_logs] LEFT OUTER JOIN [tag_tracks] ON [tag_tracks].[id] = [patient_logs].[tag_id] LEFT OUTER JOIN [areas] ON [areas].[id] = [tag_tracks].[area_id]  ORDER BY areas.title DESC OFFSET 0 ROWS FETCH NEXT 25 ROWS ONLY'
`
If `needs_order_expressions_in_select?` returns `true`, the query works as expected.

Fixes sorting on column that is not included for SQL Server

---

lib/active_scaffold/extensions/action_controller_rendering.rb

When I added wicked_pdf to my Rails app that includes active_scaffold.  I ended up getting an error when rendering because wicked_pdf also has a custom render method which gets called before the ActiveScaffold one.  In this scenario the args was an array with a single nil item.  The original code was checking for args.blank? which in this case returned false.   So later when opts.merge was executed it errored out because opts is nil.  So I replaced args.blank? with args.any? and now since args is just an array with a nil entry it returns false and opts gets correctly initialized to an empty hash and all is good.  Since we are expecting args to be an array it seems better to check for elements with any? than with blank?

Slight refactor to custom render method

---

lib/active_scaffold/attribute_params.rb
lib/active_scaffold/bridges/usa_state_select/usa_state_select_helper.rb

The multi_parameter_attributes method now uses the params_hash method from actions core to make sure it has a hash and not an ActionController::Parameters object.

Attributes (parameters) fix

---

config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/hu.yml
config/locales/ja.yml
config/locales/ru.yml
lib/active_scaffold/bridges/active_storage.rb
lib/active_scaffold/bridges/active_storage/active_storage_bridge.rb
lib/active_scaffold/bridges/active_storage/active_storage_helpers.rb
lib/active_scaffold/bridges/active_storage/form_ui.rb
lib/active_scaffold/bridges/active_storage/list_ui.rb
lib/active_scaffold/helpers/form_column_helpers.rb

closes #609
---
Once merged, just install the bridge in your initializer:
```rb
#config/initializers/active_scaffold.rb
ActiveScaffold::Bridges::ActiveStorage.install
```
---
Pictures:

Add ActiveStorage Support (609)

---

lib/active_scaffold/bridges/active_storage/active_storage_bridge.rb
lib/active_scaffold/bridges/active_storage/list_ui.rb

- Adds the missing column references used when adding thumbnails
Also:
- Allows to pass `thumb: false` to not have a thumbnail. 
- Unsolicited Reason: Currently deploying to windows :cry: and installing ImageMagick is not something we want to do at this time.
- Added Includes for Blobs as well.

ActiveStorage - Thumbnail fix + opt out for thumbnails

---

lib/active_scaffold/extensions/localize.rb

"wrong number of arguments (given 2, expected 0..1)" error message at ruby 3.0.0
https://github.com/ruby-i18n/i18n/pull/545
* ruby: 3.0.0
* rails: 6.0.3.4
* AS: master@e0a00ac
* action: index

fix i18n at ruby 3.0.0

---

lib/active_scaffold/extensions/action_view_rendering.rb
lib/active_scaffold/helpers/view_helpers.rb

When upgrading our app to rails 6.1 we encountered some issues when rendering scaffolds.  
We then downgraded to rails 6.0 and still had problems due to our use of active_scaffold_batch gem.  It appears that when views attempted to call `render :super` the partial lookup process failed.  After debugging we found this was due in part to a change in the ActionView::Template `inspect` method, and 6.0 should now use the `short_identifier` instead.
Additionally the ActionView::Helpers::RenderingHelper render method was losing the lookup context that gets set in active scaffold's render method because it uses the memoized @_view_renderer which doesn't include our @lookup_context.
This addresses these issues as well as some minor fixes for running on rails 6.1, but we will stick with 6.0 for …

Rails 6/6.1 compatibility improvements

---

app/views/active_scaffold_overrides/_form_association_record.html.erb

If a scaffold association column has its layout configured as vertical,
the subform fields are displayed vertically, except when the fields are
within a column group.  Fix by including a column_tag for each column
instead of one parent column_tag containing all the subform columns.

Display group cols vertically when col layout is vertical

---

app/views/active_scaffold_overrides/_field_search.html.erb
app/views/active_scaffold_overrides/_search.html.erb

Rails UJS apparently discards form action url query parameters when submitting a form, resulting in constraints, embedded info and eid being lost. This update adds the params as hidden fields to work around this problem.
Fixes issue #673.
I don't have any projects using jquery-ujs to test against. However, jquery-ujs supports form field values, and the form action url already contains the `search` parameter, so this shouldn't cause any problems.

Search form fixes for Rails UJS

---

lib/active_scaffold/actions/core.rb

Preventing NoMethodError:  undefined method `match?' for nil:NilClass

---

lib/active_scaffold/extensions/unsaved_record.rb

Rails >6.1 has adjusted their error object API (summary is here: https://code.lulalala.com/2020/0531-1013.html and here: https://github.com/rails/rails/blob/6-1-stable/activemodel/CHANGELOG.md#rails-610-december-09-2020).
This PR adjusts the `keeping_errors` method to work with this new API.

Adjust keeping_errors to work with rails >6.1 new error objects.

---

lib/active_scaffold/bridges/record_select/helpers.rb

https://github.com/rails/rails/issues/45165
Rails changed their `field_error_proc` in a way that breaks active scaffold. They say it's not a public API and therefore will not change it back.
This PR adjusts the usage of the `field_error_proc` to work with Rails 7 (I also think it fixes an issue in 6.1.x which backported the change from the main branch).

Adjust use of `field_error_proc` to work with Rails 7.

---

lib/active_scaffold/data_structures/column.rb
lib/active_scaffold/helpers/form_column_helpers.rb

Add a new attr_accessor to the DataStructures::Column module to allow for calling a dynamic Proc to determine whether a form column should be shown or not.
When hidden, render a dl element that can still be re-rendered by the update_columns routine so we will re-evaluate the proc whenever the column is re-rendered.
The value can be set a Proc in the scaffold controller as follows:
```
config.columns[:my_column].hide_column_if = Proc.new { |record, column, scope| record.should_be_hidden? }
```
OR to always hide, use:
```
config.columns[:my_column].hide_column_if = true
```
This is useful when you want the column to be accessible via API but do not want it to be visible in the HTML form.

Add hide_column_if Column attr_accessor

---

lib/active_scaffold/extensions/action_view_rendering.rb

When attempting to find the label for a controller rendered with the `render active_scaffold: 'path/to/controller'` helper, use the controller path to infer the scaffold controller, rather than parsing a model from the controller path, and then attempting to find the active scaffold config for that class.
Inferring the controller directly is preferable because there are cases where the controller name does not match the underlying model.  In this case when we parse the model from the controller name, we end up trying to constantize the wrong model class name, causing a NameError.
If we can't find the config from the controller name for some reason, fall back to the old behavior of pulling the model from the controller name and using active_scaffold_config_for(model)
Fixes …

Fix label lookup process when controller doesn't match model

---

lib/active_scaffold/data_structures/column.rb
lib/active_scaffold/helpers/form_column_helpers.rb

allow a scaffold controller to define a column's description attribute as a Proc, such that the description content can change depending on the current record.  This is useful when another field in the form (such as a "type" dropdown) can change the context for the record enough that the description should now reflect different information.  This would typically be used in conjunction with a column that uses update_columns to re-render other fields when it changes.

Add support for dynamic form descriptions

---

lib/active_scaffold/registry.rb

Leaning on RequestStore and thread_mattr_accessor to provide thread safe access to globalish registry items.
ref: #715

removing ActiveSupport::PerThreadRegistry

---

lib/active_scaffold/helpers/view_helpers.rb

Using `sum` on an array of objects that are not numbers doesn't make any sense.   I'm baffled that this has actually worked all this time, but when upgrading from rails 6.1 to rails 7.1, this line started throwing an appropriate error:  " Array can't be coerced into Integer"
Changed to `map` and error messages look fine.

Using `sum` on an array yields "Array can't be coerced into Integer"

---

lib/active_scaffold/data_structures/column.rb
lib/active_scaffold/helpers/form_column_helpers.rb

This PR adds support for dynamically calling a Proc defined for a column's label attribute, similar to what was recently added for column descriptions.
The Proc is passed the record, column and scope for context.
Example, which changes the label between "API Key" and "Password" depending on the record:
```
config.columns[:password].label = Proc.new { |record, column, scope| record.requires_api_key? ? 'API Key' : 'Password' }
```

Enable dynamic form labels

---

lib/active_scaffold/data_structures/action_link.rb
lib/active_scaffold/helpers/action_link_helpers.rb

This merge request would allow an action link's label to be a Proc or lambda, passing the record as the first argument.
Example usage:
```
config.nested.add_link(:accounts,
:label => Proc.new { |record| "Accounts (%i)" % record.accounts.count })
```

add support for Procs in action link labels

---

app/assets/stylesheets/active_scaffold.scss
config/locales/en.yml
lib/active_scaffold/bridges/date_picker/helper.rb

This works for me on Rails 7.2, otherwise this CSS does not load.
I also added translations for millisecond and microsecond.

Fix jquery ui datetime picker CSS and I18n
